name: Deploy aa_assist to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check for crucial files
      run: |
        if [ ! -f src/index.css ]; then echo "index.css is missing"; exit 1; fi
        if [ ! -f src/index.js ]; then echo "index.js is missing"; exit 1; fi
        if [ ! -f src/App.js ]; then echo "App.js is missing"; exit 1; fi
        if [ ! -f public/index.html ]; then echo "public/index.html is missing"; exit 1; fi

    - name: Install Dependencies
      run: npm install

    - name: Debug - Show package.json
      run: cat package.json

    - name: Debug - Show public/index.html
      run: cat public/index.html

    - name: Debug - Show src/index.css
      run: cat src/index.css

    - name: Debug - Show src/index.js
      run: cat src/index.js

    - name: Build
      run: npm run build

    - name: Debug - List build directory
      run: ls -R build

    - name: Debug - Show built index.html
      run: cat build/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./build
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

    - name: Debug - Check gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        ls -R
        cat index.html

    - name: Debug - Check GitHub Pages settings
      run: |
        echo "GitHub Pages is publishing from: $(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pages | jq -r .source.branch)"